### ISSUE TITLE
Extra dir for templates

### ISSUE THREAD

**Issue by georgringer** [jousch/TYPO3-Distribution#1]
`app/web/typo3conf/ext/theme/Resources/Private`should contain a separate dir `Templates` or `SiteTemplates`which contains then the 3 dirs:
- templates
- layouts
- partials

reason: something like *layouts* shouldn't be on same level as *language*

**Comment by jousch** [comment]
Ah ok! improved seperation. @georgringer is it ok to seperate also the view or template files for extensions? I would suggest:

`app/web/typo3conf/ext/theme/Resources/Private/Templates/Extension/News/News/Detail.html`
`app/web/typo3conf/ext/theme/Resources/Private/Templates/Extension/Felogin/FrontendLogin.html`
`app/web/typo3conf/ext/theme/Resources/Private/Templates/Layouts/Page/Layout.html`
`app/web/typo3conf/ext/theme/Resources/Private/Templates/Partials/Page/Foo.html`
`app/web/typo3conf/ext/theme/Resources/Private/Templates/Templates/Page/Default.html`

What about renaming `app/web/typo3conf/ext/theme/Resources/Private/Templates/` to `app/web/typo3conf/ext/theme/Resources/Private/View/` for better understanding?

**Comment by georgringer** [comment]
yeah IMO fine

**Comment by jousch** [comment]
actual the intellij fluid plugin just support the default fluid paths. Maybe it will be configurable in future versions of the plugin. Until then, I recommend to keep defaults.
