### ISSUE TITLE
ImageManipulationWizard: add 3:2 crop ratio

### ISSUE THREAD

**Issue by jousch** [jousch/TYPO3-Distribution#82]
Since the change by @helhum in the TYPO3 core https://github.com/TYPO3/TYPO3.CMS/commit/063938393d793d7e4b0261da8fe709073a815ae9 I had to remove the predefined ratios.

First, I will try to get the 3:2 ratio into the core directly. if that gets rejected, I have to add it here in my distribution

**Comment by helhum** [comment]
where did you define these ratios? in `Configuration/TCA`?

**Comment by helhum** [comment]
if that is the case, then there might be a bug in the tca migration

**Comment by jousch** [comment]
Thx for your reply @helhum. No, I found the migration after disabling it in my site package extension.

But anyway, if I understand correct, actually it's not possible to add imageRatios globally like before?

**Comment by helhum** [comment]
> actually it's not possible to add imageRatios globally like before

don't understand what you mean. Actually your TCA should have been migrated to show the ratios as configured.

With the new cropper configuration happens at the exact same place in TCA, just that you have more options to configure

**Comment by jousch** [comment]
Ah, ok, I understand now! Georg has enlightened me :-]
